<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbReference_M_ORDER_ARC" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://xmlns.oracle.com/cpqcloud/parts" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="Resources/dbReference_M_ORDER_ARC_table.xsd"/>
            <oracle-xsl-mapper:rootElement name="MOrderArcCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbReference_M_ORDER_ARC"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="fgl_cpq_demo_parts.wsdl"/>
            <oracle-xsl-mapper:rootElement name="modifyParts" namespace="http://xmlns.oracle.com/cpqcloud/parts"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [MON SEP 10 14:49:35 JST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--この行より下のユーザー編集が許可されています - この行を削除しないでください-->
   <xsl:template match="/">
      <tns:modifyParts>
         <tns:Parts>
            <tns:each_record>
               <tns:company_associations>
                  <xsl:value-of select="&quot;cpq-10183&quot;"/>
               </tns:company_associations>
               <tns:part_number>
                  <xsl:value-of select="/ns0:MOrderArcCollection/ns0:MOrderArc/ns0:spordOdkey2"/>
               </tns:part_number>
               <tns:direct_buy>
                  <xsl:value-of select="&quot;1&quot;"/>
               </tns:direct_buy>
               <tns:description>
                  <tns:en>
                     <xsl:value-of select="/ns0:MOrderArcCollection/ns0:MOrderArc/ns0:spordOdMei"/>
                  </tns:en>
                  <tns:ja_JP>
                     <xsl:value-of select="/ns0:MOrderArcCollection/ns0:MOrderArc/ns0:spordOdMei"/>
                  </tns:ja_JP>
               </tns:description>
               <tns:lead_time>
                  <xsl:value-of select="&quot;-1&quot;"/>
               </tns:lead_time>
               <tns:part_display_number>
                  <xsl:value-of select="/ns0:MOrderArcCollection/ns0:MOrderArc/ns0:spordOdkey2"/>
               </tns:part_display_number>
            </tns:each_record>
         </tns:Parts>
      </tns:modifyParts>
   </xsl:template>
</xsl:stylesheet>